- name: Install firewall
  yum:
    name: firewalld
    state: latest

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Allow elasticsearch on firewalld
  firewalld:
    service: elasticsearch
    immediate: true
    permanent: true
    state: enabled
    