- name: Allocate sufficient file descriptors per process and allocate sufficient threads per user
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nofile 65536
      * hard nofile 65536 
      * soft nproc 4096
      * hard nproc 4096 

- name: Disable swap memory
  shell: swapoff -a